using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// La información general de un ensamblado se controla mediante el siguiente 
// conjunto de atributos. Cambie estos valores de atributo para modificar la información
// asociada con un ensamblado.
[assembly: AssemblyTitle("OnlineReceiptPrintingApp")]
[assembly: AssemblyDescription("Application that allows interaction with thermal printers to print sales receipts generated by an Online Point of Sale System.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("BHERSEG - Freelance Website Development")]
[assembly: AssemblyProduct("OnRePriApp - Online Receipt Printing App")]
[assembly: AssemblyCopyright("Copyright ©  2025")]
[assembly: AssemblyTrademark("Copyright © 2025 RepriApp. All rights reserved.")]
[assembly: AssemblyCulture("")]

// Si establece ComVisible en false, los tipos de este ensamblado no estarán visibles 
// para los componentes COM.  Si es necesario obtener acceso a un tipo en este ensamblado desde 
// COM, establezca el atributo ComVisible en true en este tipo.
[assembly: ComVisible(false)]

// El siguiente GUID sirve como id. de typelib si este proyecto se expone a COM.
[assembly: Guid("d245f23e-a601-4a13-897e-3ed6ead7ee9d")]

// La información de versión de un ensamblado consta de los cuatro valores siguientes:
//
//      Versión principal
//      Versión secundaria
//      Número de compilación
//      Revisión
//
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
